site_name: FANTASTX Documentation
docs_dir: Docs
theme: material

# Repository
repo_name: MaterialEyes/fantastx
repo_url: https://github.com/MaterialEyes/fantastx

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
  - mkdocs-jupyter
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MaterialEyes/fantastx

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - custom.css

nav:
  - Home: home.md
  - Installation: installation.md
  - FAQs: FAQs.md
  - Usage: USAGE.md
  - Citation: citation.md
  - FANTASTX YAML Preparation: YAML_PREP.md
  - XANES YAML inputs: xanes.md
  - API:
      - run_ops: run_ops-reference.md
      - inputs: inputs-reference.md
      - energy: energy-reference.md
      - epsilonSelection: epsilonSelection-reference.md
      - clusteredSelection: clusteredSelection-reference.md
      - selection: selection-reference.md
      - fingerprinting: fingerprinting-reference.md
      - clustering: clustering-reference.md
      - distance_check: distance_check-reference.md
      - structure_operations: structure_operations-reference.md
      - structure_record: structure_record-reference.md
      - experimental_simulation: experimental_simulation-reference.md
