"""
This module contains classes to manage the structures, their corresponding
attributes and evaluated data.

Also contains general functions (if any required)
"""

from __future__ import division, unicode_literals, print_function
from pymatgen.core.structure import Structure, Lattice
from pymatgen.core.composition import Composition

import os


class register_id(object):
    """
    An object to assign a unique label to each model.
    """

    def __init__(self):
        """
        When first initialized, the object has a value of 0.
        """
        self.label = 0

    def create_id(self):
        """
        Each time that the object is asked to create an ID, it
        increments its own value by 1, and returns its value.

        Returns:

            int: the object ID
        """
        self.label += 1
        return self.label


class model(object):
    """
    The object which corresponds to each atomic configuration generated by
    FANTASTX. The `model` object stores as attributes the following
    items:

    - The ID (`label`)
    - The pymatgen `Structure` object (`astr`)
    - The evolutionary inheritance (`inheritance`)
    - Experimental simulation functions (ie `Xsim1`)
    - Total energy after relaxation (`tot_en`)
    - All objective function values (ie `obj0_val`)
    - Various selection related qualities, including `selection_prob`
        for [distance from pareto selection](../selection-reference)
        selection, `rank` and `cluster_rank` for [clustered selection]
        (../clusteredSelection-reference), and `cluster` for
        [$\epsilon$ selection](../epsilonSelection-reference) and
        [clustered selection](../clusteredSelection-reference).
    - Fingerprinting information (`fingerprint` and `features`)
    """

    def __init__(self, astr, reg_id):
        """
        Given a structure object, makes model object assuming defaults for all
        attributes (see above for a description of each attribute). Most
        attributes are initialized as ```python None```.

        Arguments:

            astr (obj): `pymatgen.core.structure.Structure` object

            reg_id (obj): `register_id` object
        """

        # id of the model
        # age is also known by id number
        self.label = reg_id.create_id()
        # pymatgen structure object
        self.astr = astr
        # To save middle interface grain gor gb model
        self.gb_iface = None
        # where the structure came from (list of ints)
        self.inheritance = None
        self.made_by = None
        self.relax_path = None
        # set exp sim functions as variables
        self.Xsim1 = None
        self.Xsim2 = None
        self.Xsim3 = None
        self.Xsim4 = None
        # total energy after relaxation
        self.tot_en = None
        # Used if vasp is energy_code to resubmit calculation
        self.converged = None  # used
        # energy objective value (like gamma or adsorption energy)
        self.obj0_val = None
        # exp_sim objective values
        # NOTE: 1, 2, 3, 4 are decided internally at the beginning
        self.obj1_val = 0
        self.obj2_val = 0
        self.obj3_val = 0
        self.obj4_val = 0
        self.num_of_obj = 1
        # (single or multi objective function) overall value
        self.overall_val = None
        # selection probability based on overall_val
        # gets updated after every new added strucutre
        self.selection_prob = None
        # non-domination rank overall and within the cluster. Used for
        # clusteredSelection
        self.rank = None
        self.cluster_rank = None
        # cluster to which the model belongs. Used for epsilonSelection
        # and clusteredSelection
        self.cluster = None
        # How many times this structure is selected from get_parent()
        self.times_chosen_as_parent = 0
        # Selective dynamics z-coordinates for gb or slab models
        # NOTE: If only sd_true_above is provided -
        # 1. sd_true_below is set to hollow_top_z for gb models
        # 2. all atoms above sd_true_above are set to True for slab models
        self.sd_true_above = None
        self.sd_true_below = None
        # fingerprinting information
        self.fingerprint = {}
        self.features = None

        # if the model corresponds to a molecule, store the fragment
        # representation of the model for genetic operations
        self.molecule_representation = None


class structure_constraints(object):
    """
    Object which determines all relevant structural constraints for the
    specified geometry (the `shape`). Currently, the supported geometries
    are: ['cluster', 'molecule', 'gb', 'surface']. The constraints which
    are common to all of these geometries are:

    - **species**: dictionary which *must* be included as part of the
        `str_record` input dictionary. The only mandatory field is the species
        `name`. Other information such as the minimum or maximum number of
        atoms of that species are optional, and will otherwise set according
        to internal defaults of:

        - min_num_atoms: 30
        - max_num_atoms: 101
        - min_dist: 2 angstroms
        - max_dist: 5 angstroms

        See the [guide to YAML prep](../YAML_PREP/#mandatory-inputs_1) for a
        description of how to feed
        this information into FANTASTX.

    - **max_bond_dist**: maximum separation that one atom can have from all
        other atoms.

    Other parameters are geometry specific. For instance, the parameters
    for the `cluster` geometry are:

    - **box_abc**: the lattice constants of the box bounding the cluster.
    - **max_dia**: the maximum diameter of the cluster
    - **origin**: the cartesian coordinates of the cluster center.

    The `molecule` geometry has one added parameter:

    - **fixed_species**: species whose atoms need to be kept fixed
        during basin-hopping.

    The `surface` and `gb` geometries have more complicated parameters. For
    more information, refer to the [guide to YAML prep](
    ../YAML_PREP/#mandatory-inputs_1).

    """

    def __init__(self, str_record):
        """
        Arguments:

            str_record (dict): dictionary of all the parameters from
            YAML input file under `structure_record` keyword.
        """

        self.def_min_dist = 2  # min distance between atoms in angstroms
        self.def_max_dist = 5  # min distance which should contain one+ bond
        self.min_num_atoms = 30
        self.max_num_atoms = 101
        self.max_bond_dist = 4
        self.max_bonds_per_atom_default = 2

        if 'max_bond_dist' in str_record:
            self.max_bond_dist = str_record['max_bond_dist']

        # save details of all species as a dict
        # DU
        if 'species' not in str_record:
            print('species - names, atoms and min_dist are not mentioned'
                  ' in input file. These are mandatory!')
        else:
            species_dict = str_record['species']
            self.num_species = len(species_dict)

        # see that all attributes for all species are present by placing
        # defaults for species1 and that of species1 for the rest
        # DU
        element_syms = {}
        i = 1
        found_species = []
        max_bonds = {}
        for species, values in species_dict.items():
            while species != "species" + str(i):
                print('Error. Cannot find species ' + str(i) +
                      '. Please check the input format for species')
                i += 1
                if i == 50:
                    break
            found_species.append(i)
            if 'name' not in values:
                print(
                    'Please specify element name (Ex: \'Al\') of specie '
                    + str(i) + '.')
            element_syms[i] = values['name']
            if 'min_num' not in values:
                values['min_num'] = self.min_num_atoms
            elif i == 1:
                self.min_num_atoms = values['min_num']
            if 'max_num' not in values:
                values['max_num'] = self.max_num_atoms
            elif i == 1:
                self.max_num_atoms = values['max_num']
            if 'max_bonds' in values:
                max_bonds[values['name']] = values['max_bonds']
            else:
                max_bonds[values['name']] = self.max_bonds_per_atom_default

            setattr(self, species, values)
            i += 1

        self.element_syms = element_syms

        # grab max number of bonds if provided

        # DU
        # make a min_dist dictionary with default min_dist for all bonds
        self.min_dist_dict = {}
        self.max_dist_dict = {}
        for index, sp1 in enumerate(found_species):
            for sp2 in found_species[index:]:
                key = 'sp' + str(sp1) + '_sp' + str(sp2)
                self.min_dist_dict[key] = self.def_min_dist
                self.max_dist_dict[key] = self.def_max_dist
                if 'min_dist' in str_record:
                    if key in str_record['min_dist'].keys():
                        self.min_dist_dict[key] = str_record['min_dist'][key]
                if 'max_dist' in str_record:
                    if key in str_record['max_dist'].keys():
                        self.max_dist_dict[key] = str_record['max_dist'][key]

        # shape and related
        if 'cluster' in str_record:
            self.shape = 'cluster'
        elif 'gb' in str_record:
            self.shape = 'gb'
        elif 'surface' in str_record:
            self.shape = 'surface'
        elif 'molecule' in str_record:
            self.shape = 'molecule'
        elif 'bulk' in str_record:
            self.shape = 'bulk'
        # TODO: add other shapes here

        # ########################bulk parameters begin########################
        if self.shape == 'bulk':
            if 'box_abc' in str_record['bulk']:
                self.box_abc = str_record['bulk']['box_abc']
            else:
                print('The lattice lengths of the box are not specified.'
                      ' Using default equal side lengths of a=b=c=10Å')
                self.box_abc = [10, 10, 10]

            if 'box_angles' in str_record['bulk']:
                self.box_angles = str_record['bulk']['box_angles']
            else:
                print('The lattice angles of the box are not specified.'
                      ' Using default orthogonal angles of 90 degrees.')
                self.box_angles = [90, 90, 90]

            if len(max_bonds) != 0:
                self.max_bonds = max_bonds
        # ###################bulk parameters end###############################

        # ########################cluster parameters begin#####################
        if self.shape == 'cluster':
            if 'box_abc' in str_record['cluster']:
                self.box_abc = str_record['cluster']['box_abc']
            else:
                print('The lattice lengths of the box are not specified.'
                      ' Using default orthogonal box of a=b=c=20Å')
                self.box_abc = [20, 20, 20]

            if 'max_dia' in str_record['cluster']:
                self.max_dia = str_record['cluster']['max_dia']
            else:
                print('The maximum diameter of the cluster is not specified. '
                      'Using default diameter of 8Å')
                self.max_dia = 8

            if 'origin' in str_record['cluster']:
                self.origin = str_record['cluster']['origin']
            else:
                self.origin = [i/2. for i in self.box_abc]

            if len(max_bonds) != 0:
                self.max_bonds = max_bonds
        # ###################cluster parameters ends###########################

        # ########################gb parameters begins#########################
        if self.shape == 'gb':
            init_gb_astr_path = str_record['gb']['init_gb_astr']
            self.init_gb_astr = Structure.from_file(init_gb_astr_path)
            if 'iface_thickness' in str_record['gb']:
                self.iface_thickness = str_record['gb']['iface_thickness']
            else:
                self.iface_thickness = 10  # angstroms
            if 'iface_z_mid' in str_record['gb']:
                self.iface_z_mid = str_record['gb']['iface_z_mid']
            else:
                self.iface_z_mid = 0.5  # assuming default mid as 0.5

            gb_latt_matrix = self.init_gb_astr.lattice.matrix
            self.iface_latt = Lattice([gb_latt_matrix[0],
                                       gb_latt_matrix[1],
                                       [0, 0, self.iface_thickness]])
            self.num_slices = 2
            if 'num_slices' in str_record['gb']:
                self.num_slices = str_record['gb']['num_slices']

            self.hop_mate_frac = 0.5
            if 'hop_mate_frac' in str_record['gb']:
                self.hop_mate_frac = str_record['gb']['hop_mate_frac']

            self.sd_true_above = None
            if 'sd_true_above' in str_record['gb']:
                self.sd_true_above = str_record['gb']['sd_true_above']
            self.sd_true_below = None
            if 'sd_true_below' in str_record['gb']:
                self.sd_true_below = str_record['gb']['sd_true_below']

            """
            We get best matched gb interface structure from ingrained.
            For ingrained, this grain data needs to be provided.
            Grain data is not required for Fantastx.

            self.grain1_data = None # {'orientation': (1,1,1),
                                       'tilt': 15, 'name': Al}
            #self.grain1_orientation =
            #self.grain1_tilt =
            self.grain2_data = None # {'orientation': (1,1,0),
                                       'tilt': -10, 'name': Ge}
            #self.grain2_orientation =
            #self.grain2.tilt =
            """
        # ######################## gb parameters ends #########################

        # #################### surface parameters begins ######################
        if self.shape == 'surface':
            surface_params = str_record['surface']
            init_slabs_dir = surface_params['init_slabs_dir']
            poscars = [init_slabs_dir + '/' + i for i in
                       os.listdir(init_slabs_dir)
                       if i.startswith('POSCAR_slab')]
            init_slabs_dict = {}
            for p in range(len(poscars)):
                init_slabs_dict[p+1] = poscars[p]

            self.init_slabs_dict = init_slabs_dict

            if 'surface_thickness' in surface_params:
                self.surface_thickness = surface_params['surface_thickness']

            if 'substrate_thickness' in surface_params:
                self.substrate_thickness = \
                    surface_params['substrate_thickness']

            if 'separation' in surface_params:
                self.separation = surface_params['separation']

            if 'constrain_z' in surface_params:
                self.constrain_z = surface_params['constrain_z']

            if 'sd_cut_off' in surface_params:
                self.sd_cut_off = surface_params['sd_cut_off']

            if 'sd_no_z' in surface_params:
                self.sd_no_z = surface_params['sd_no_z']

            if 'composition' in surface_params:
                composition = Composition(surface_params['composition'])
                self.comp_dict = composition.to_reduced_dict

            if 'num_slices' in surface_params:
                self.num_slices = surface_params['num_slices']

            if 'hop_mate_frac' in surface_params:
                self.hop_mate_frac = surface_params['hop_mate_frac']

        # ##################### surface parameters ends #######################

        # ################### molecule parameters begins ######################
        if self.shape == 'molecule':
            if 'box_abc' in str_record['molecule']:
                self.box_abc = str_record['molecule']['box_abc']
            else:
                print('The lattice lengths of the box are not specified.'
                      ' Using default orthogonal box of a=b=c=20Å')
                self.box_abc = [20, 20, 20]

            if 'max_dia' in str_record['molecule']:
                self.max_dia = str_record['molecule']['max_dia']
            else:
                print('The maximum diameter of the molecule is not specified. '
                      'Using default diameter of 8Å')
                self.max_dia = 8

            if 'origin' in str_record['molecule']:
                self.origin = str_record['molecule']['origin']
            else:
                self.origin = [i/2. for i in self.box_abc]

            if 'fixed_species' in str_record['molecule']:
                self.fixed_species = str_record['molecule']['fixed_species']
            else:
                print('No species were specified as being held fixed. '
                      'Using default setting of [].')
                self.fixed_species = []

            if 'fragments_yaml' in str_record['molecule']:
                self.fragments_yaml = str_record['molecule']['fragments_yaml']
            else:
                print('No fragment yaml provided. No random molecule generation '
                      'will be possible')
            if 'fragments_directory' in str_record['molecule']:
                self.fragments_directory =\
                    str_record['molecule']['fragments_directory']
            else:
                print('No fragment directory provided. No random molecule'
                      ' generation will be possible')

    def get_constraints(self):
        """
        Returns a dictionary of all the constraints stored in the object.
        These constraints can be used in [structure_operations]
        (../structure_operations-reference).
        """

        return self.__dict__


##
